services:
  - type: web
    name: countdown-email
    env: python
    buildCommand:
      - apt-get update && apt-get install -y libjpeg-dev zlib1g-dev
      - pip install --upgrade pip setuptools wheel
      - pip install -r countdown_email/requirements.txt
    startCommand: gunicorn app:app

